In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Data Overview

In [ ]:
df=pd.read_csv("/content/airline_passenger_satisfaction.csv")

In [ ]:
df.head()

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction
0,1,Male,48,First-time,Business,Business,821,2,5.0,3,...,3,5,2,5,5,5,3,5,5,Neutral or Dissatisfied
1,2,Female,35,Returning,Business,Business,821,26,39.0,2,...,5,4,5,5,3,5,2,5,5,Satisfied
2,3,Male,41,Returning,Business,Business,853,0,0.0,4,...,3,5,3,5,5,3,4,3,3,Satisfied
3,4,Male,50,Returning,Business,Business,1905,0,0.0,2,...,5,5,5,4,4,5,2,5,5,Satisfied
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3,...,3,4,4,5,4,3,3,3,3,Satisfied

In [ ]:
df.shape

(129880, 24)

In [ ]:
df.dtypes

ID                                          int64
Gender                                     object
Age                                         int64
Customer Type                              object
Type of Travel                             object
Class                                      object
Flight Distance                             int64
Departure Delay                             int64
Arrival Delay                             float64
Departure and Arrival Time Convenience      int64
Ease of Online Booking                      int64
Check-in Service                            int64
Online Boarding                             int64
Gate Location                               int64
On-board Service                            int64
Seat Comfort                                int64
Leg Room Service                            int64
Cleanliness                                 int64
Food and Drink                              int64
In-flight Service                           int64
In-flight Wifi Service                      int64
In-flight Entertainment                     int64
Baggage Handling                            int64
Satisfaction                               object
dtype: object

In [ ]:
df.columns.to_list()

['ID',
 'Gender',
 'Age',
 'Customer Type',
 'Type of Travel',
 'Class',
 'Flight Distance',
 'Departure Delay',
 'Arrival Delay',
 'Departure and Arrival Time Convenience',
 'Ease of Online Booking',
 'Check-in Service',
 'Online Boarding',
 'Gate Location',
 'On-board Service',
 'Seat Comfort',
 'Leg Room Service',
 'Cleanliness',
 'Food and Drink',
 'In-flight Service',
 'In-flight Wifi Service',
 'In-flight Entertainment',
 'Baggage Handling',
 'Satisfaction']

Basic Statistics

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129880 entries, 0 to 129879
Data columns (total 24 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   ID                                      129880 non-null  int64
 1   Gender                                  129880 non-null  object
 2   Age                                     129880 non-null  int64
 3   Customer Type                           129880 non-null  object
 4   Type of Travel                          129880 non-null  object
 5   Class                                   129880 non-null  object
 6   Flight Distance                         129880 non-null  int64
 7   Departure Delay                         129880 non-null  int64
 8   Arrival Delay                           129487 non-null  float64
 9   Departure and Arrival Time Convenience  129880 non-null  int64
 10  Ease of Online Booking                  129880 non-null  int64
 11  Check-in Service                        129880 non-null  int64
 12  Online Boarding                         129880 non-null  int64
 13  Gate Location                           129880 non-null  int64
 14  On-board Service                        129880 non-null  int64
 15  Seat Comfort                            129880 non-null  int64
 16  Leg Room Service                        129880 non-null  int64
 17  Cleanliness                             129880 non-null  int64
 18  Food and Drink                          129880 non-null  int64
 19  In-flight Service                       129880 non-null  int64
 20  In-flight Wifi Service                  129880 non-null  int64
 21  In-flight Entertainment                 129880 non-null  int64
 22  Baggage Handling                        129880 non-null  int64
 23  Satisfaction                            129880 non-null  object
dtypes: float64(1), int64(18), object(5)
memory usage: 23.8+ MB

In [ ]:
df.describe()

,ID,Age,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,Ease of Online Booking,Check-in Service,Online Boarding,Gate Location,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling
count,129880.000000,129880.000000,129880.000000,129880.000000,129487.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000
mean,64940.500000,39.427957,1190.316392,14.713713,15.091129,3.057599,2.756876,3.306267,3.252633,2.976925,3.383023,3.441361,3.350878,3.286326,3.204774,3.642193,2.728696,3.358077,3.632114
std,37493.270818,15.119360,997.452477,38.071126,38.465650,1.526741,1.401740,1.266185,1.350719,1.278520,1.287099,1.319289,1.316252,1.313682,1.329933,1.176669,1.329340,1.334049,1.180025
min,1.000000,7.000000,31.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,32470.750000,27.000000,414.000000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,3.000000
50%,64940.500000,40.000000,844.000000,0.000000,0.000000,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,3.000000,3.000000,4.000000,3.000000,4.000000,4.000000
75%,97410.250000,51.000000,1744.000000,12.000000,13.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,5.000000
max,129880.000000,85.000000,4983.000000,1592.000000,1584.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

Check missing values

In [ ]:
df.isnull().mean()*100

ID                                        0.000000
Gender                                    0.000000
Age                                       0.000000
Customer Type                             0.000000
Type of Travel                            0.000000
Class                                     0.000000
Flight Distance                           0.000000
Departure Delay                           0.000000
Arrival Delay                             0.302587
Departure and Arrival Time Convenience    0.000000
Ease of Online Booking                    0.000000
Check-in Service                          0.000000
Online Boarding                           0.000000
Gate Location                             0.000000
On-board Service                          0.000000
Seat Comfort                              0.000000
Leg Room Service                          0.000000
Cleanliness                               0.000000
Food and Drink                            0.000000
In-flight Service                         0.000000
In-flight Wifi Service                    0.000000
In-flight Entertainment                   0.000000
Baggage Handling                          0.000000
Satisfaction                              0.000000
dtype: float64

Drop Missing Values

In [ ]:
df = df.dropna(subset=['Arrival Delay'])

In [ ]:
df.isnull().sum()

ID                                        0
Gender                                    0
Age                                       0
Customer Type                             0
Type of Travel                            0
Class                                     0
Flight Distance                           0
Departure Delay                           0
Arrival Delay                             0
Departure and Arrival Time Convenience    0
Ease of Online Booking                    0
Check-in Service                          0
Online Boarding                           0
Gate Location                             0
On-board Service                          0
Seat Comfort                              0
Leg Room Service                          0
Cleanliness                               0
Food and Drink                            0
In-flight Service                         0
In-flight Wifi Service                    0
In-flight Entertainment                   0
Baggage Handling                          0
Satisfaction                              0
dtype: int64

Rename Column Name

In [ ]:
df = df.rename(columns={
    'ID':'id',
    'Gender': 'gender',
    'Age': 'age',
    'Customer Type': 'customer_type',
    'Type of Travel': 'travel_type',
    'Class': 'travel_class',
    'Flight Distance': 'flight_distance',
    'Departure Delay': 'departure_delay',
    'Arrival Delay': 'arrival_delay',
    'Departure and Arrival Time Convenience': 'time_convenience',
    'Ease of Online Booking': 'online_booking',
    'Check-in Service': 'checkin_service',
    'Online Boarding': 'online_boarding',
    'Gate Location': 'gate_location',
    'On-board Service': 'onboard_service',
    'Seat Comfort': 'seat_comfort',
    'Leg Room Service': 'legroom_service',
    'Cleanliness': 'cleanliness',
    'Food and Drink': 'food_drink',
    'In-flight Service': 'inflight_service',
    'In-flight Wifi Service': 'inflight_wifi_service',
    'In-flight Entertainment': 'inflight_entertainment',
    'Baggage Handling': 'baggage_handling',
    'Satisfaction': 'satisfaction'
})

In [ ]:
df.columns.to_list()

['id',
 'gender',
 'age',
 'customer_type',
 'travel_type',
 'travel_class',
 'flight_distance',
 'departure_delay',
 'arrival_delay',
 'time_convenience',
 'online_booking',
 'checkin_service',
 'online_boarding',
 'gate_location',
 'onboard_service',
 'seat_comfort',
 'legroom_service',
 'cleanliness',
 'food_drink',
 'inflight_service',
 'inflight_wifi_service',
 'inflight_entertainment',
 'baggage_handling',
 'satisfaction']

Remove Irrelevant Column

In [ ]:
df.drop(columns=['id'],inplace=True)

In [ ]:
df.head()

,gender,age,customer_type,travel_type,travel_class,flight_distance,departure_delay,arrival_delay,time_convenience,online_booking,...,onboard_service,seat_comfort,legroom_service,cleanliness,food_drink,inflight_service,inflight_wifi_service,inflight_entertainment,baggage_handling,satisfaction
0,Male,48,First-time,Business,Business,821,2,5.0,3,3,...,3,5,2,5,5,5,3,5,5,Neutral or Dissatisfied
1,Female,35,Returning,Business,Business,821,26,39.0,2,2,...,5,4,5,5,3,5,2,5,5,Satisfied
2,Male,41,Returning,Business,Business,853,0,0.0,4,4,...,3,5,3,5,5,3,4,3,3,Satisfied
3,Male,50,Returning,Business,Business,1905,0,0.0,2,2,...,5,5,5,4,4,5,2,5,5,Satisfied
4,Female,49,Returning,Business,Business,3470,0,1.0,3,3,...,3,4,4,5,4,3,3,3,3,Satisfied

In [ ]:
df.shape

(129487, 23)

Change Data type

In [ ]:
df.dtypes

gender                     object
age                         int64
customer_type              object
travel_type                object
travel_class               object
flight_distance             int64
departure_delay             int64
arrival_delay             float64
time_convenience            int64
online_booking              int64
checkin_service             int64
online_boarding             int64
gate_location               int64
onboard_service             int64
seat_comfort                int64
legroom_service             int64
cleanliness                 int64
food_drink                  int64
inflight_service            int64
inflight_wifi_service       int64
inflight_entertainment      int64
baggage_handling            int64
satisfaction               object
dtype: object

In [ ]:
df["arrival_delay"] = df["arrival_delay"].astype(int)

In [ ]:
df.dtypes

gender                    object
age                        int64
customer_type             object
travel_type               object
travel_class              object
flight_distance            int64
departure_delay            int64
arrival_delay              int64
time_convenience           int64
online_booking             int64
checkin_service            int64
online_boarding            int64
gate_location              int64
onboard_service            int64
seat_comfort               int64
legroom_service            int64
cleanliness                int64
food_drink                 int64
inflight_service           int64
inflight_wifi_service      int64
inflight_entertainment     int64
baggage_handling           int64
satisfaction              object
dtype: object

In [ ]:
from google.colab import files
df.to_csv('airline_satisfaction_cleaned.csv', index=False)
files.download('airline_satisfaction_cleaned.csv')